# Generated by Django 4.2.1 on 2023-09-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('General Group', 'General Group'), ('Youth Group', 'Youth Group'), ('Women Group', 'Women Group')], max_length=35),
        ),
    ]
