# Generated by Django 4.2.1 on 2023-09-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0002_alter_group_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='nationality_of_members',
        ),
        migrations.AddField(
            model_name='group',
            name='status_of_members',
            field=models.CharField(choices=[('Refugees', 'Refugees'), ('National', 'National'), ('Mixed', 'Mixed')], default='Refugees', max_length=25),
        ),
    ]
