# Generated by Django 4.2.1 on 2023-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0003_remove_group_nationality_of_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chairperson_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
