# Generated by Django 4.2.1 on 2023-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0004_alter_group_chairperson_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='region',
            field=models.CharField(choices=[('South West', 'South West'), ('West Nile', 'West Nile'), ('Karamoja', 'Karamoja')], max_length=100),
        ),
    ]
