# Generated by Django 4.2.1 on 2023-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0005_alter_beneficiary_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='nationality',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('Congo', 'Congo'), ('Sundan', 'Sundan'), ('South Sudan', 'South Sudan')], max_length=100),
        ),
    ]
