# Generated by Django 4.2.1 on 2023-09-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0006_alter_beneficiary_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='household_head_phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='participant_age',
            field=models.IntegerField(max_length=2),
        ),
    ]
