# Generated by Django 4.2.1 on 2023-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0007_alter_beneficiary_household_head_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='gender_of_participant',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
