# Generated by Django 4.2.1 on 2023-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0008_alter_beneficiary_gender_of_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='sex_hhh',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gender_hhh',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='disablity_of_hhh',
            field=models.CharField(choices=[('Able bodied', 'Able bodied'), ('Living with a disabioity', 'Living with a disabioity')], max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='education_level',
            field=models.CharField(choices=[('Illiterate', 'Illiterate'), ('Primaryn education', 'Primaryn education'), ('Secondary/High school education', 'Secondary/High school education'), ('Teritary education', 'Teritary education')], max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='relationship_with_household_head',
            field=models.CharField(choices=[('Head of household', 'Head of household'), ('Spouse/partner', 'Spouse/partner'), ('Son/daughter', 'Son/daughter'), ('Brother/sister', 'Brother/sister'), ('Father/mother', 'Father/mother')], max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='religion',
            field=models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Traditional African religion', 'Traditional African religion'), ('Atheist', 'Atheist')], max_length=100),
        ),
    ]
