# Generated by Django 4.2.1 on 2023-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0009_remove_beneficiary_sex_hhh_beneficiary_gender_hhh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='household_id',
            field=models.CharField(max_length=12),
        ),
    ]
