# Generated by Django 4.2.1 on 2023-09-28 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0010_alter_beneficiary_household_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='participant_age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99, message='Maximum age should be 99 years or less.'), django.core.validators.MinValueValidator(0, message='Age cannot be negative.')]),
        ),
    ]
