# Generated by Django 4.2.1 on 2023-09-28 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0011_alter_beneficiary_participant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='household_head_phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999, message='9 digits maximum')]),
        ),
    ]
