# Generated by Django 4.2.1 on 2023-09-28 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0013_alter_beneficiary_age_of_hhh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='age_of_hhh',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99, message='Maximum age should be 99 years or less.'), django.core.validators.MinValueValidator(0, message='Age cannot be negative.')], verbose_name='Age of HH Head'),
        ),
    ]
