# Generated by Django 4.2.1 on 2023-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0014_alter_beneficiary_age_of_hhh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semcmentoringcoaching',
            name='component',
            field=models.CharField(default='SEMC', max_length=10),
        ),
    ]
