# Generated by Django 4.2.1 on 2023-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0016_alter_semccommunityparticipation_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfi',
            name='component',
            field=models.CharField(default='LPD', max_length=10),
        ),
        migrations.AlterField(
            model_name='lpdnonfarm',
            name='component',
            field=models.CharField(default='LPD', max_length=10),
        ),
        migrations.AlterField(
            model_name='lpdofffarm',
            name='component',
            field=models.CharField(default='LPD', max_length=10),
        ),
        migrations.AlterField(
            model_name='lpdonfarm',
            name='component',
            field=models.CharField(default='LPD', max_length=10),
        ),
        migrations.AlterField(
            model_name='semcsbcc',
            name='component',
            field=models.CharField(default='SEMC', max_length=10),
        ),
        migrations.AlterField(
            model_name='spgfa',
            name='component',
            field=models.CharField(default='SP', max_length=10),
        ),
        migrations.AlterField(
            model_name='spnutricash',
            name='component',
            field=models.CharField(default='SP', max_length=10),
        ),
        migrations.AlterField(
            model_name='spsage',
            name='component',
            field=models.CharField(default='SP', max_length=10),
        ),
    ]
