# Generated by Django 4.2.1 on 2023-09-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0017_alter_dfi_component_alter_lpdnonfarm_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semcsbcc',
            name='date',
        ),
    ]
