# Generated by Django 4.2.1 on 2023-09-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0018_remove_semcsbcc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spgfa',
            name='date',
        ),
    ]
