# Generated by Django 4.2.1 on 2023-09-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0019_remove_spgfa_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spgfa',
            old_name='Disbursement_date',
            new_name='disbursement_date',
        ),
    ]
