# Generated by Django 4.2.1 on 2023-09-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0021_spgfa_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spnutricash',
            name='date',
        ),
    ]
