# Generated by Django 4.2.1 on 2023-09-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0022_remove_spnutricash_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spnutricash',
            old_name='Disbursement_date',
            new_name='disbursement_date',
        ),
    ]
