# Generated by Django 4.2.1 on 2023-10-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0024_spnutricash_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spsage',
            name='date',
        ),
    ]
