# Generated by Django 4.2.1 on 2023-10-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0025_remove_spsage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spsage',
            old_name='Disbursement_date',
            new_name='disbursement_date',
        ),
    ]
