# Generated by Django 4.2.1 on 2023-10-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0026_rename_disbursement_date_spsage_disbursement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpdonfarm',
            old_name='Disbursement_date',
            new_name='value_date',
        ),
        migrations.RemoveField(
            model_name='lpdonfarm',
            name='date',
        ),
    ]
