# Generated by Django 4.2.1 on 2023-10-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0027_rename_disbursement_date_lpdonfarm_value_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfi',
            name='district',
            field=models.CharField(choices=[('Koboko', 'Koboko'), ('Lamwo', 'Lamwo'), ('Isingiro', 'Isingiro'), ('Kamwenge', 'Kamwenge')], default='Koboko', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lpdnonfarm',
            name='district',
            field=models.CharField(choices=[('Koboko', 'Koboko'), ('Lamwo', 'Lamwo'), ('Isingiro', 'Isingiro'), ('Kamwenge', 'Kamwenge')], default='Koboko', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lpdofffarm',
            name='district',
            field=models.CharField(choices=[('Koboko', 'Koboko'), ('Lamwo', 'Lamwo'), ('Isingiro', 'Isingiro'), ('Kamwenge', 'Kamwenge')], default='Koboko', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lpdonfarm',
            name='district',
            field=models.CharField(choices=[('Koboko', 'Koboko'), ('Lamwo', 'Lamwo'), ('Isingiro', 'Isingiro'), ('Kamwenge', 'Kamwenge')], default='Koboko', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spsage',
            name='district',
            field=models.CharField(choices=[('Koboko', 'Koboko'), ('Lamwo', 'Lamwo'), ('Isingiro', 'Isingiro'), ('Kamwenge', 'Kamwenge')], default='Koboko', max_length=100),
            preserve_default=False,
        ),
    ]
