# Generated by Django 4.2.1 on 2023-10-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0028_dfi_district_lpdnonfarm_district_lpdofffarm_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpdofffarm',
            old_name='Disbursement_date',
            new_name='value_date',
        ),
        migrations.RemoveField(
            model_name='lpdofffarm',
            name='date',
        ),
    ]
