# Generated by Django 4.2.1 on 2023-10-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0029_rename_disbursement_date_lpdofffarm_value_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfi',
            old_name='Disbursement_date',
            new_name='value_date',
        ),
        migrations.RenameField(
            model_name='lpdnonfarm',
            old_name='Disbursement_date',
            new_name='value_date',
        ),
        migrations.RemoveField(
            model_name='dfi',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lpdnonfarm',
            name='date',
        ),
    ]
