# Generated by Django 4.2.1 on 2023-10-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0030_rename_disbursement_date_dfi_value_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpdnonfarm',
            old_name='nonOfffarm_Hardware_component_received',
            new_name='nonfarm_Hardware_component_received',
        ),
    ]
