# Generated by Django 4.2.1 on 2023-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0032_remove_group_female_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='other_partner_assistance',
            field=models.CharField(choices=[('None', 'None'), ('ACF', 'ACF'), ('ALIGHT', 'ALIGHT'), ('AVSC', 'AVSC'), ('CONVOID', 'CONVOID'), ('DRDIP', 'DRDIP'), ('Equity Bank', 'Equity Bank'), ('FRC', 'FRC'), ('Government through DRDIP', 'Government through DRDIP'), ('HIJRA', 'HIJRA'), ('HFU', 'HFU'), ('Isingiro DLG', 'Isingiro DLG'), ('Nsamis (pigglets) 2022', 'Nsamis (pigglets) 2022'), ('OPM', 'OPM'), ('OPPORTUNITY BANK', 'OPPORTUNITY BANK'), ('OXFAM', 'OXFAM'), ('RIPPLE EFFECT', 'RIPPLE EFFECT'), ('SACU', 'SACU'), ('SEND A COW', 'SEND A COW'), ('Shared Action Africa', 'Shared Action Africa'), ('UNDP', 'UNDP'), ('Usabiti- Digitalization of savings, records', 'Usabiti- Digitalization of savings, records'), ('VEDCO', 'VEDCO'), ('WFP', 'WFP'), ('UWESO', 'UWESO')], max_length=255),
        ),
    ]
