# Generated by Django 4.2.1 on 2023-11-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0034_alter_beneficiary_disablity_of_hhh'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='participant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
