# Generated by Django 4.2.1 on 2023-11-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSMIS', '0036_alter_beneficiary_participant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='participant_photo',
            field=models.FileField(blank=True, null=True, upload_to='beneficiary_photos/'),
        ),
    ]
