# Generated by Django 4.2.1 on 2024-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='actual_ID_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='actual_district',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='actual_nationality',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='actual_region',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='actual_settlement',
            field=models.CharField(max_length=40),
        ),
    ]
