# Generated by Django 4.2.1 on 2024-05-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0003_alter_spnutricashdetails_actual_id_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spnutricashdetails',
            options={},
        ),
    ]
