# Generated by Django 4.2.1 on 2024-05-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0004_alter_spnutricashdetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='ID_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_id_number_details', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='ID_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_id_type_details', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_district_details', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_nationality_details', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='nutricash_beneficiary_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_details', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_region_details', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_settlement_details', to='SERMIS.nutricashbeneficiary'),
        ),
    ]
