# Generated by Django 4.2.1 on 2024-05-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0005_alter_spnutricashdetails_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='ID_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_id_number', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='ID_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_id_type', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_district', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_nationality', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='nutricash_beneficiary_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_beneficiaryname', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_region', to='SERMIS.nutricashbeneficiary'),
        ),
        migrations.AlterField(
            model_name='spnutricashdetails',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_settlement', to='SERMIS.nutricashbeneficiary'),
        ),
    ]
