# Generated by Django 4.2.1 on 2024-05-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0007_nutricashbeneficiary_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spsagedetails',
            name='actual_ID_number',
            field=models.CharField(default=3, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spsagedetails',
            name='actual_ID_type',
            field=models.CharField(default='3', max_length=40),
            preserve_default=False,
        ),
    ]
