# Generated by Django 4.2.1 on 2024-05-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0008_spsagedetails_actual_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spsagedetails',
            name='ID_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sage_id_number', to='SERMIS.sagebeneficiary'),
        ),
        migrations.AlterField(
            model_name='spsagedetails',
            name='ID_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sage_id_type', to='SERMIS.sagebeneficiary'),
        ),
    ]
