# Generated by Django 4.2.1 on 2024-05-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0010_rename_actual_id_number_spsagedetails_actual_candidate_individual_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spsagedetails',
            name='actual_nationality',
            field=models.CharField(default='Congo', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spsagedetails',
            name='nationality',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='sage_nationality', to='SERMIS.beneficiary'),
            preserve_default=False,
        ),
    ]
