# Generated by Django 4.2.1 on 2024-05-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0011_spsagedetails_actual_nationality_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DFI',
            new_name='FinLitDetails',
        ),
    ]
