# Generated by Django 4.2.1 on 2024-05-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0012_rename_dfi_finlitdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finlitdetails',
            options={'verbose_name_plural': 'FinLit Details'},
        ),
        migrations.RemoveField(
            model_name='finlitdetails',
            name='name_of_participant',
        ),
        migrations.AddField(
            model_name='finlitdetails',
            name='finlit_candidate_name',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='finlit_candidate', to='SERMIS.finlitbeneficiary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finlitdetails',
            name='group_representative',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='finlit_details_group_representative', to='SERMIS.beneficiary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finlitdetails',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finlit_district', to='SERMIS.finlitbeneficiary'),
        ),
        migrations.AlterField(
            model_name='finlitdetails',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finlit_group', to='SERMIS.group'),
        ),
        migrations.AlterField(
            model_name='finlitdetails',
            name='provider',
            field=models.CharField(choices=[('WFP', 'WFP'), ('AFI', 'AFI'), ('KRC', 'KRC'), ('ACF', 'ACF'), ('FHI', 'FHI'), ('MTI', 'MTI'), ('LWF', 'LWF'), ('FHU', 'FHU')], max_length=10),
        ),
        migrations.AlterField(
            model_name='finlitdetails',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finlit_region', to='SERMIS.finlitbeneficiary'),
        ),
        migrations.AlterField(
            model_name='finlitdetails',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finlit_settlement', to='SERMIS.finlitbeneficiary'),
        ),
    ]
