# Generated by Django 4.2.1 on 2024-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0013_alter_finlitdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finlitbeneficiary',
            name='actual_district',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='finlitbeneficiary',
            name='actual_nationality',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='finlitbeneficiary',
            name='actual_region',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='finlitbeneficiary',
            name='actual_settlement',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
