# Generated by Django 4.2.1 on 2024-05-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0014_finlitbeneficiary_actual_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finlitdetails',
            name='actual_nationality',
            field=models.CharField(default='1', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finlitdetails',
            name='nationality',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='finlit_nationality', to='SERMIS.nutricashbeneficiary'),
            preserve_default=False,
        ),
    ]
