# Generated by Django 4.2.1 on 2024-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0016_alter_finlitdetails_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='lpd_component',
            field=models.CharField(choices=[('On-Farm', 'On-Farm'), ('Off-farm', 'Off-farm'), ('Non-farm', 'Non-farm')], default='On-Farm', max_length=10),
            preserve_default=False,
        ),
    ]
