# Generated by Django 4.2.1 on 2024-05-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0017_beneficiary_lpd_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semccommunityparticipation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_participation_group', to='SERMIS.beneficiary'),
        ),
    ]
