# Generated by Django 4.2.1 on 2024-05-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0018_alter_semccommunityparticipation_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semcmentoringcoaching',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_coaching_group', to='SERMIS.beneficiary'),
        ),
    ]
