# Generated by Django 4.2.1 on 2024-05-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0019_alter_semcmentoringcoaching_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semcsbcc',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbcc_group', to='SERMIS.beneficiary'),
        ),
    ]
