# Generated by Django 4.2.1 on 2024-05-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0020_alter_semcsbcc_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='spgfa',
            name='actual_nationality',
            field=models.CharField(default='Congo', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spgfa',
            name='nationality',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='gfa_nationality', to='SERMIS.beneficiary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spgfa',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfa_group', to='SERMIS.beneficiary'),
        ),
    ]
