# Generated by Django 4.2.1 on 2024-05-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0022_alter_lpdonfarm_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpdnonfarm',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lpd_nonfarm_group', to='SERMIS.beneficiary'),
        ),
        migrations.AlterField(
            model_name='lpdofffarm',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lpd_offfarm_group', to='SERMIS.beneficiary'),
        ),
    ]
