# Generated by Django 4.2.1 on 2024-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0023_alter_lpdnonfarm_group_alter_lpdofffarm_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='lpd_component',
            field=models.CharField(choices=[('On-farm', 'On-farm'), ('Off-farm', 'Off-farm'), ('Non-farm', 'Non-farm')], max_length=10),
        ),
    ]
