# Generated by Django 4.2.1 on 2024-05-20 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0024_alter_beneficiary_lpd_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='profiling_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
