# Generated by Django 4.2.1 on 2024-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0025_beneficiary_profiling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='profiling_date',
            field=models.DateTimeField(),
        ),
    ]
