# Generated by Django 4.2.1 on 2024-05-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0026_alter_beneficiary_profiling_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='gfa_status',
            field=models.CharField(choices=[('Enrolled in GFA', 'Enrolled in GFA'), ('Not enrolled in GFA', 'Not enrolled in GFA'), ('Exited from GFA', 'Exited from GFA')], default='Enrolled in GFA', max_length=35),
        ),
    ]
