# Generated by Django 4.2.1 on 2024-05-20 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0027_beneficiary_gfa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profiling_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
