# Generated by Django 4.2.1 on 2024-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0028_group_profiling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='household_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
