# Generated by Django 4.2.1 on 2024-05-27 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0029_alter_beneficiary_household_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiling_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('family_member_name', models.CharField(max_length=50)),
                ('family_member_dob', models.DateField()),
                ('family_member_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('ID_type', models.CharField(choices=[('NIN', 'NIN'), ('Attestation Individual Number', 'Attestation Individual Number'), ('KSRN Number', 'KSRN Number'), ('Next of Kin NIN', 'Next of Kin NIN'), ('Next of Kin AIN', 'Next of Kin AIN'), ('Other government issued ID', 'Other government issued ID')], default='NIN', max_length=30)),
                ('family_member_individual_id', models.CharField(max_length=12)),
                ('pregnant_or_lactating', models.CharField(choices=[('None', 'None'), ('Pregnant', 'Pregnant'), ('Lactating', 'Lactating'), ('Pregnant & Lactating', 'Pregnant & Lactating')], default='None', max_length=22)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_nationality', models.CharField(blank=True, max_length=35)),
                ('actual_region', models.CharField(blank=True, max_length=35)),
                ('actual_district', models.CharField(blank=True, max_length=35)),
                ('actual_settlement', models.CharField(blank=True, max_length=35)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_district', to='SERMIS.beneficiary')),
                ('group_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_group_representative', to='SERMIS.beneficiary')),
                ('household_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_household_id', to='SERMIS.beneficiary')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_nationality', to='SERMIS.beneficiary')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_region', to='SERMIS.beneficiary')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_settlement', to='SERMIS.beneficiary')),
            ],
        ),
    ]
