# Generated by Django 4.2.1 on 2024-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0030_familymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricashbeneficiary',
            name='expected_delivery_date',
            field=models.DateField(null=True),
        ),
    ]
