# Generated by Django 4.2.1 on 2024-05-27 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SERMIS', '0031_alter_nutricashbeneficiary_expected_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricashbeneficiary',
            name='ID_number',
        ),
        migrations.AddField(
            model_name='nutricashbeneficiary',
            name='candidate_individual_id',
            field=models.CharField(default='2', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutricashbeneficiary',
            name='household_id',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='nutricash_beneficiaries_household_id', to='SERMIS.beneficiary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutricashbeneficiary',
            name='enrollment_gestational_age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99, message='2 digits maximum')]),
        ),
    ]
